apiVersion: apps/v1
kind: Deployment
metadata:
  name: p13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p13
  template:
    metadata:
      labels:
        app: p13
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p13
        ports:
        - containerPort: 80
